mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 24 18:14:45 2018

@author: edoardoguerriero
"""

from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<str:farmer_name>/get_farmerList/', views.get_farmerList, name='nameslist')
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
    
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

       
class Farmer(models.Model):
    farmer_name = models.CharField("Farmer's name", max_length=50)
    number_animal_owned = models.IntegerField()
    last_request_date = models.DateTimeField('Last request')
    
    def __str__(self):
       return self.name
    
class Animal(models.Model):
    species = models.CharField("Aminal's fspecies", max_length = 15)
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    time_since_request = models.DurationField()
    symptom = models.CharField("Symptom description", max_length=200)
    first_day_sickness = models.DateTimeField('Time passed from last request')
    
    
    def __str__(self):
       return self.symptom

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
#from django.template import loader

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    context_object_name
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
    


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    ... # same as above, no changes needed.
    
    
def get_farmerList(request, farmer_name):
    return HttpResponse("<h1>List of animals of " + farmer_name + "</h1>)
    

polls/templates/polls/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="1561.4">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 16.0px; font: 14.0px Helvetica; color: #0c4b33; -webkit-text-stroke: #0c4b33; background-color: #f8f8f8}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 16.0px; font: 14.0px Helvetica; color: #0c4b33; -webkit-text-stroke: #0c4b33; background-color: #f8f8f8; min-height: 17.0px}
    span.s1 {font-kerning: none}
  </style>
</head>
<body>
<p class="p1"><span class="s1">&lt;h1&gt;{{ question.question_text }}&lt;/h1&gt;</span></p>
<p class="p2"><span class="s1"></span><br></p>
<p class="p1"><span class="s1">{% if error_message %}&lt;p&gt;&lt;strong&gt;{{ error_message }}&lt;/strong&gt;&lt;/p&gt;{% endif %}</span></p>
<p class="p2"><span class="s1"></span><br></p>
<p class="p1"><span class="s1">&lt;form action="{% url 'polls:vote' question.id %}" method="post"&gt;</span></p>
<p class="p1"><span class="s1">{% csrf_token %}</span></p>
<p class="p1"><span class="s1">{% for choice in question.choice_set.all %}</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">    </span>&lt;input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" /&gt;</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">    </span>&lt;label for="choice{{ forloop.counter }}"&gt;{{ choice.choice_text }}&lt;/label&gt;&lt;br /&gt;</span></p>
<p class="p1"><span class="s1">{% endfor %}</span></p>
<p class="p1"><span class="s1">&lt;input type="submit" value="Vote" /&gt;</span></p>
<p class="p1"><span class="s1">&lt;/form&gt;</span></p>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="1561.4">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 14.0px; font: 12.0px Helvetica; color: #000000; -webkit-text-stroke: #000000}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 14.0px; font: 14.0px Helvetica; color: #0c4b33; -webkit-text-stroke: #0c4b33}
    span.s1 {font-kerning: none}
    span.s2 {font: 12.0px Helvetica; font-kerning: none; color: #000000; -webkit-text-stroke: 0px #000000}
    span.s3 {font-kerning: none; background-color: #f8f8f8}
  </style>
</head>
<body>
<p class="p1">{% load static %}</p>
<p class="p2"><br></p>
<p class="p1">&lt;link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /&gt;</p>
<p class="p3"><span class="s1">{% if latest_question_list %}</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">    </span>&lt;ul&gt;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">    </span>{% for question in latest_question_list %}</span></p>
<p class="p4"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s3">&lt;li&gt;&lt;a href="{% url 'polls:detail' question.id %}"&gt;{{ question.question_text }}&lt;/a&gt;&lt;/li&gt;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">    </span>{% endfor %}</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">    </span>&lt;/ul&gt;</span></p>
<p class="p3"><span class="s1">{% else %}</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">    </span>&lt;p&gt;No polls are available.&lt;/p&gt;</span></p>
<p class="p3"><span class="s1">{% endif %}</span></p>
</body>
</html>